Module1 task2
htmlacademy-yii/114077-task-force-1 pull request #2
Opened 2020-01-18 15:48 UTC by fohunoff

2020-01-19 00:40 UTC, raidkon requested changes
ты пропустил момент:

Для проверки класса, вам понадобится написать тестовый сценарий, который:
Подключит класс и создаст его объект.
Вызовет методы объекта и проверит, что результат верный.

2020-01-19 09:13 UTC, fohunoff commented
Добавил тест на один из методов (из задания)

2020-01-21 16:31 UTC, raidkon requested changes
Необходимо сделать проверки на все методы.

2020-01-21 16:31 UTC, raidkon commented on tests/TaskTest.php
> +        $income = $task->getNextStatus('ACTION_CANCEL');
Тут необходимо использовать заданные тобой константы.

2020-01-21 16:36 UTC, raidkon requested changes

2020-01-21 16:36 UTC, raidkon commented on src/Task.php
> +    ];
Такие вещи рекомендуется делать методами, а не свойствами.

А если делаешь свойствами то тогда не публичными.

Значение публичных свойств можно изменить из вне тем самым повлиять на работу объекта.

2020-01-21 16:36 UTC, raidkon commented on src/Task.php
> +        'ACTION_CANCEL' => 'STATUS_CANCEL',
Везде где можно лучше всегда использовать константы, а не хардкодить. Тем самым бы ты избежал ошибки когда у тебя названия действия/сататусов в константах и списке разные.

2020-01-21 16:36 UTC, raidkon commented on src/Task.php
> +    private $id_client;
рекомендуется делать наименование $client_id а не id_client

2020-01-21 16:36 UTC, raidkon commented on src/Task.php
> +        return $this->next_statuses[$action];
нет проверки на существование индекса

2020-01-26 18:34 UTC, merged